$(document).ready(function()
{
	$("#sps").click(function(){
		window.open("sps.html");
	});
	$("#handcricket").click(function(){
		window.open("handcricket.html");
	});
	$("#tictactoe").click(function(){
		window.open("tictactoe.html");
	});
	$("#puzzle").click(function(){
		window.open("puzzle.html");
	});
	$("#bullsncows").click(function(){
		window.open("bullsncows.html");
	});
	$("#flipcard").click(function(){
		window.open("flipcard.html");
	});
	$("#battleships").click(function(){
		window.open("battleships.html");
	});
	$("#minesweeper").click(function(){
		window.open("minesweeper.html");
	});
});